export const INVENTORY_PERMISSIONS = [
  "warehouse.read",
  "warehouse.create",
  "warehouse.update",
  "warehouse.delete",
  "location.read",
  "location.create",
  "location.update",
  "location.delete",
  "stock.read",
  "stock.create",
  "stock.update",
  "stock.delete",
  "stock_movement.read",
  "stock_movement.create",
  "stock_movement.update",
  "stock_movement.delete",
  "transfer.read",
  "transfer.create",
  "transfer.update",
  "transfer.delete",
  "inventory_count.read",
  "inventory_count.create",
  "inventory_count.update",
  "inventory_count.delete",
] as const;
