export const SALES_PERMISSIONS = [
  "customer.read",
  "customer.create",
  "customer.update",
  "customer.delete",
  "order.read",
  "order.create",
  "order.update",
  "order.delete",
  "quotation.read",
  "quotation.create",
  "quotation.update",
  "quotation.delete",
  "sales_team.read",
  "sales_team.create",
  "sales_team.update",
  "sales_team.delete",
  "pricing_rule.read",
  "pricing_rule.create",
  "pricing_rule.update",
  "pricing_rule.delete",
] as const;
