export const FINANCE_PERMISSIONS = [
  "account.read",
  "account.create",
  "account.update",
  "account.delete",
  "invoice.read",
  "invoice.create",
  "invoice.update",
  "invoice.delete",
  "payment.read",
  "payment.create",
  "payment.update",
  "payment.delete",
  "budget.read",
  "budget.create",
  "budget.update",
  "budget.delete",
  "journal_entry.read",
  "journal_entry.create",
  "journal_entry.update",
  "journal_entry.delete",
  "tax_config.read",
  "tax_config.create",
  "tax_config.update",
  "tax_config.delete",
] as const;
