export const CRM_PERMISSIONS = [
  "contact.read",
  "contact.create",
  "contact.update",
  "contact.delete",
  "lead.read",
  "lead.create",
  "lead.update",
  "lead.delete",
  "opportunity.read",
  "opportunity.create",
  "opportunity.update",
  "opportunity.delete",
  "campaign.read",
  "campaign.create",
  "campaign.update",
  "campaign.delete",
  "activity.read",
  "activity.create",
  "activity.update",
  "activity.delete",
] as const;
