export const PROCUREMENT_PERMISSIONS = [
  "supplier.read",
  "supplier.create",
  "supplier.update",
  "supplier.delete",
  "purchase_requisition.read",
  "purchase_requisition.create",
  "purchase_requisition.update",
  "purchase_requisition.delete",
  "purchase_order.read",
  "purchase_order.create",
  "purchase_order.update",
  "purchase_order.delete",
  "rfq.read",
  "rfq.create",
  "rfq.update",
  "rfq.delete",
  "goods_receipt.read",
  "goods_receipt.create",
  "goods_receipt.update",
  "goods_receipt.delete",
] as const;
