import { ModuleConfig } from "@kwim/shared-ui";
import {
  Users,
  Wallet,
  UserPlus,
  GraduationCap,
  LayoutDashboard,
  UserCog,
  Building,
  CalendarCheck,
  FileText,
  FolderKanban,
  Bell,
  Settings,
  HandCoins,
} from "lucide-react";

export const hrModuleConfig: ModuleConfig = {
  name: "hr",
  displayName: "Digital HRS",
  icon: Users,
  baseUrl: "/hr",

  quickActions: [
    {
      icon: Users,
      label: "New Employee",
      description: "Add a new employee",
      onClick: () => console.log("New employee"),
    },
    {
      icon: Wallet,
      label: "Run Payroll",
      description: "Process payroll",
      onClick: () => console.log("Run payroll"),
    },
  ],

  menu: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/",
    },
    {
      id: "company-management",
      label: "Company Management",
      icon: Building,
      path: "/company",
      children: [
        { id: "company", label: "Company", path: "/company" },
        { id: "branch", label: "Branch", path: "/company/branch" },
        { id: "department", label: "Department", path: "/company/department" },
        { id: "post", label: "Post", path: "/company/post" },
      ],
    },
    {
      id: "user-management",
      label: "User Management",
      icon: UserCog,
      path: "/users",
      children: [
        { id: "users-list", label: "Users", path: "/users" },
      ],
    },
    {
      id: "employee-management",
      label: "Employee Management",
      icon: Users,
      path: "/employees",
      children: [
        { id: "employees", label: "Employees", path: "/employees" },
        { id: "location-logs", label: "Location Logs", path: "/employees/location-logs" },
        { id: "logout-requests", label: "Logout Requests", path: "/employees/logout-requests" },
        { id: "employee-card-template", label: "Employee Card Template", path: "/employees/card-template" },
      ],
    },
    {
      id: "attendance-section",
      label: "Attendance Section",
      icon: CalendarCheck,
      path: "/attendance",
      children: [
        { id: "attendance", label: "Attendance", path: "/attendance" },
        { id: "attendance-logs", label: "Attendance Logs", path: "/attendance/logs" },
        { id: "attendance-report", label: "Attendance Report", path: "/attendance/report" },
      ],
    },
    {
      id: "project-management",
      label: "Project Management",
      icon: FolderKanban,
      path: "/projects",
      children: [
        { id: "project", label: "Project", path: "/projects" },
        { id: "tasks", label: "Tasks", path: "/projects/tasks" },
        { id: "clients", label: "Clients", path: "/projects/clients" },
      ],
    },
    {
      id: "notice",
      label: "Notice",
      icon: Bell,
      path: "/notice",
    },
    {
      id: "payroll-management",
      label: "Payroll Management",
      icon: Wallet,
      path: "/payroll",
      children: [
        { id: "payroll", label: "Payroll", path: "/payroll" },
        { id: "payroll-setting", label: "Payroll Setting", path: "/payroll/setting" },
        { id: "advance-salary", label: "Advance Salary", path: "/payroll/advance-salary" },
        { id: "employee-salary", label: "Employee Salary", path: "/payroll/employee-salary" },
        { id: "tax-report", label: "Tax report", path: "/payroll/tax-report" },
        { id: "tasks-payroll", label: "Tasks", path: "/payroll/tasks" },
      ],
    },
    {
      id: "loan-management",
      label: "Loan Management",
      icon: HandCoins,
      path: "/loans",
      children: [
        { id: "loan-type", label: "Loan Type", path: "/loans/type" },
        { id: "loan-list", label: "Loan List", path: "/loans" },
      ],
    },
    {
      id: "leave-management",
      label: "Leave Management",
      icon: FileText,
      path: "/leave",
      children: [
        { id: "leave-type", label: "Leave Type", path: "/leave/type" },
        { id: "leave-request", label: "Leave Request", path: "/leave/request" },
        { id: "leave-balance", label: "Leave Balance", path: "/leave/balance" },
      ],
    },
    {
      id: "recruitment",
      label: "Recruitment",
      icon: UserPlus,
      path: "/recruitment",
      children: [
        { id: "job-postings", label: "Job Postings", path: "/recruitment/jobs" },
        { id: "candidates", label: "Candidates", path: "/recruitment/candidates" },
        { id: "interviews", label: "Interviews", path: "/recruitment/interviews" },
      ],
    },
    {
      id: "training",
      label: "Training",
      icon: GraduationCap,
      path: "/training",
      children: [
        { id: "training-programs", label: "Training Programs", path: "/training/programs" },
        { id: "training-sessions", label: "Sessions", path: "/training/sessions" },
        { id: "certifications", label: "Certifications", path: "/training/certifications" },
      ],
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      path: "/settings",
      gap: true,
    },
  ],

  routes: [],

  permissions: [
    "company.read", "company.create", "company.update", "company.delete",
    "branch.read", "branch.create", "branch.update", "branch.delete",
    "employee.read", "employee.create", "employee.update", "employee.delete",
    "user.read", "user.create", "user.update", "user.delete",
    "role.read", "role.create", "role.update", "role.delete",
    "department.read", "department.create", "department.update", "department.delete",
    "post.read", "post.create", "post.update", "post.delete",
    "attendance.read", "attendance.create", "attendance.update", "attendance.delete",
    "project.read", "project.create", "project.update", "project.delete",
    "task.read", "task.create", "task.update", "task.delete",
    "client.read", "client.create", "client.update", "client.delete",
    "notice.read", "notice.create", "notice.update", "notice.delete",
    "payroll.read", "payroll.create", "payroll.update", "payroll.delete",
    "loan.read", "loan.create", "loan.update", "loan.delete",
    "leave.read", "leave.create", "leave.update", "leave.delete",
    "recruitment.read", "recruitment.create", "recruitment.update", "recruitment.delete",
    "training.read", "training.create", "training.update", "training.delete",
    "settings.read", "settings.update",
  ],
};
