export const MANUFACTURING_PERMISSIONS = [
  "bom.read",
  "bom.create",
  "bom.update",
  "bom.delete",
  "manufacturing_order.read",
  "manufacturing_order.create",
  "manufacturing_order.update",
  "manufacturing_order.delete",
  "work_center.read",
  "work_center.create",
  "work_center.update",
  "work_center.delete",
  "operation.read",
  "operation.create",
  "operation.update",
  "operation.delete",
  "quality_check.read",
  "quality_check.create",
  "quality_check.update",
  "quality_check.delete",
] as const;
