// Re-export everything from @kwim/core
export {
  CrudPage,
  CrudTable,
  CrudForm,
  ActionBar,
  DynamicFormFields,
  ModuleDashboard,
  ImageUploadField,
  TabbedForm,
  RelationalField,
  createFullEntityPage,
  createGroupedModule,
  createEntityApi,
  createListPage,
  setApiClient,
  getApiClient,
} from "@kwim/core";

export type {
  CrudConfig,
  CrudPermissions,
  Action,
  CrudFilterSelect,
  CrudFilterSelectOption,
  FieldConfig,
  SelectOption,
  DashboardConfig,
  StatCardConfig,
  ChartConfig,
  FormTab,
  RelationalFieldProps,
  FullEntityPageConfig,
  ServiceName,
  ModuleEntityConfig,
  GroupedModuleConfig,
} from "@kwim/core";
